modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/MCMC-Dev/MCMC-Mod/issues"
license = "GNU LGPLv2.1"

[[mods]]
modId = "mcmcmod"
version = "${file.jarVersion}"
displayName = "MCMC Mod"
authors = "LatvianModder"
description='''
Collects analytics data and sends crash reports to modpack authors
'''
url="https://mcmc.dev/about"

[[dependencies.mcmc]]
    modId="forge"
mandatory = true
versionRange = "[32,)"
ordering = "NONE"
    side="BOTH"

[[dependencies.mcmc]]
    modId="minecraft"
mandatory = true
versionRange = "[1.16.2,)"
ordering = "NONE"
    side="BOTH"
