modLoader="javafml"
loaderVersion="[26,)"
issueTrackerURL="https://github.com/MCMC-Dev/MCMC-Mod/issues"

[[mods]]
modId="mcmc"
version = "${file.jarVersion}"
displayName = "MCMC Mod"
authors = "LatvianModder"
description='''
Collects analytics data and sends crash reports to modpack authors
'''
url="https://mcmc.dev/about"

[[dependencies.mcmc]]
    modId="forge"
    mandatory=true
    versionRange="[26,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mcmc]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14,)"
    ordering="NONE"
    side="BOTH"
